export default {
    // main section
    // html
    'Goroxels': 'Goroxels',
    'CHAT': 'CHAT',
    'login to chat': 'login to chat',
    'template': 'template',
    'template url': 'template url',
    'template opacity': 'template opacity',
    'settings': 'settings',
    'game settings': 'game settings',
    'open window': 'open window',
    'account settings': 'account settings',
    'change name': 'change name',
    'logout': 'logout',
    'toolbinds settings': 'toolbinds settings',
    'ui settings': 'ui settings',
    'tools': 'tools',
    'online': 'online',
    'Send alerts': 'Send alerts',
    // js and others
    // tools subsection
    'clicker': 'clicker',
    'protector': 'protector',
    'alt protector': 'alt protector',
    'mover': 'mover',
    'floodfill': 'floodfill',
    'pipette': 'pipette',
    'alt pipette': 'alt pipette',
    'coords to chat': 'coords to chat',
    'pixel info': 'pixel info',
    'swap colors': 'swap colors',
    'left color': 'left color',
    'right color': 'right color',
    'toggle chat': 'toggle chat',
    'toggle menu': 'toggle menu',
    'toggle everything': 'toggle everything',
    'ctrlZ': 'ctrlZ',
    'grid': 'grid',
    'paste': 'paste',
    'template 0/N opaq': 'template 0/N opaq',
    'template 1/N opaq': 'template 1/N opaq',
    'square': 'square',
    '+brush size': '+brush size',
    '-brush size': '-brush size',
    'copy': 'copy',
    // end tools subsection
    'colors size': 'colors size',
    'palette width': 'palette width',
    'hide emojis': 'hide emojis',
    'emoji list': 'emoji list',
    'super secret button': 'super secret button',
    'show placed pixels': 'show placed pixels',
    'show patterns over the palette': 'show patterns over the palette',
    'more emojis!': 'more emojis!',
    'show protected': 'show protected',
    'brush size': 'brush size',
    'max saved pixels': 'max saved pixels',
    'disable chat colors': 'disable chat colors',
    'chat messages limit': 'chat messages limit',
    'light grid': 'light grid',
    'enable grid': 'enable grid',
    'draw line length': 'draw line length',
    'Case insensitive, 0/o i/l are same': 'Case insensitive, 0/o i/l are same',
    'Can\'t recognize?': 'Can\'t recognize?',
    'Captcha': 'Captcha',
    'search users': 'search users',
    'OR': 'OR',
    'banned?': 'banned?',
    'convert image into palette': 'convert image into palette',
    'save canvas': 'save canvas',
    'intro.introHeader': 'Where am I?',
    // help
    'intro.introHeader': 'where am I',
    'how to play?': 'how to play?',
    'tools': 'tools',
    'intro.tools2header': 'underground tools',
    'intro.desc': ' - an online pixel canvas, made with love.',
    'intro.desc2': 'You can draw <b>without registration</b>. But if you register, you\'ll be able to paint <b>even faster</b> (+you\'ll unlock chat and some tools. And a +5 luck bonus)',
    'intro.howToPlayDecs': 'It\'s trivial: choose a color below, click on the canvas - a pixel will appear. Very simple. <br><i>but that\'s far from all</i>👁️',
    'intro.toolsDecs': 'To make life easier and grass greener, we\'ve made some features:<br><i>P.S. All keys can be remapped in settings. If you\'re on mobile, many tools are available for selection from the top left</i>',
    'intro.toolsClicker': '<b>Clicker</b><br>YES, it clicks. NO, it won\'t draw for you. [Space]<br>',
    'intro.toolsAS': '<b>Back and forth</b><br>You can quickly switch colors using [A] and [S]',
    'intro.toolC': '<b>Eyedropper</b><br>The game has an eyedropper [C]',
    'intro.brush': '<b>Brush</b><br>For those who behaved well, a larger drawing tool is available<br>',
    'intro.line': '<b>Line</b><br>For straight-edge guys [Shift]',
    'intro.flood': '<b>Fill</b><br>Stop feeding me lines! [F]<br>',
    'intro.resetColors': '<b>Reset selected color</b><br>with a simple hand movement [RMB] (right click)',
    'intro.grid': '<b>Grid</b><br>toggled with [G]',
    'intro.ctrlZ': '<b>Undo</b><br>You can even undo pixels! Key: [Z]<br>',
    'intro.tools2desc': 'These are additional tools, but that only makes them cooler!!',
    'intro.toolsHiders': '<b>Hide unnecessary stuff</b><br>from the interface with separate keybinds. [K] hides chat, [L] hides the top panel, and [;] hides everything at once',
    'intro.multicol': '<b>Multicolor</b><br>For advanced users, we\'ve added multicolor support - when the brush paints with two colors simultaneously, alternating them. <br>Why? Some images with <a href="//en.wikipedia.org/wiki/Dithering" target="_blank">dithering</a> are much easier to draw this way. Worth trying.',
    'intro.multicol2': 'Select second color [RMB] on palette color/[Alt+C] on canvas.',
    'intro.multicol3': '(Mixed up the order? Just press [X])',
    'intro.sendCoords': '<b>Send coordinates to chat</b><br>by pressing [U]',
    'intro.templateTools': '<b>Template</b><br>has its own binds too! [O] and [P] instantly switch its transparency.<br>You can also move the template by holding [Ctrl] and [LMB]',
    'intro.templateIntro': 'Wanderer, you\'ve come so far! Well then, I\'ll share a secret...',
    'intro.templateDesc': 'The principle is simple and, if it helps, roughly the same as pxls.space. <br>You paste a direct image link in the URL field (top left), enter the desired coordinates and draw over it',
    'intro.templateDescConvert': '<b>But my image isn\'t in the palette :(</b><br>If you want it in palette - go to <a href="/convert" target="_blank">/convert</a>. Paste your image in the input field at the top.',
    'intro.templateDescReminder': '<b>BY THE WAY</b><br>you can draw exactly like in this video. Want to do the same? Go to <a href="/convert" target="_blank">/convert</a> (convert to pattern -> [upload image to imgur])<br>'+
        '<i>P.S. Better set template opacity to maximum.</i><br>'+
        '<i>P.P.S. if the link is red - you\'ll have to upload manually. Instructions: </i><a href="//vk.cc/cOCbAd" target="_blank">vk.cc/cOCbAd</a>',
    'intro.authorHeader': 'author',
    'intro.authorText':'Authors - Gorokh and Comrades',
    'intro.authorContacts': '<img src="./img/telegram.svg" style="vertical-align:middle;height:40px">&nbsp;<a href="//t.me/antieden">Telegram</a><br>'+
    '<img src="./img/discord-logo-circle.svg" style="vertical-align:middle;height:40px">&nbsp;goeden<br>'+
    '<img src="./img/discord-logo-circle.svg" style="vertical-align:middle;height:40px">&nbsp;<a href="//discord.gg/FeBMmwRUpA">Game server</a>',
    // nsfw modal
    'WARNING': 'WARNING',
    'This canvas may contain illustrations, inappropriate for people under age of 18, including:': 'This canvas may contain illustrations, inappropriate for people under age of 18, including:',
    'Gore, furry, porn, hate, anime and all possible variations of these.': 'Gore, furry, porn, hate, anime and all possible variations of these.',
    'Are you 18 y.o. and fully understanding what are you doing?': 'Are you 18 y.o. and fully understanding what are you doing?',
    'I am 18 years old and I take responsibility for my psyche on myself': 'I am 18 years old and I take responsibility for my psyche on myself',	
    // converter section
    // html
    'Convert!': 'Convert!',
    'Into palette': 'Into palette',
    'GO!': 'GO!',
    'Dithering': 'Dithering',
    'None': 'None',
    'Floyd-Steinberg': 'Floyd-Steinberg',
    'Stuсki': 'Stuсki',
    'Chess': 'Chess',
    'Ordered (matrix)': 'Ordered (matrix)',
    'Threshold': 'Threshold',
    'Matrix size': 'Matrix size',
    'Darken': 'Darken',
    'Lighten': 'Lighten',
    'Balance': 'Balance',
    'Color function for ΔE': 'Color function for ΔE',
    'RGB + luminance [very fast and dirty]': 'RGB + luminance [very fast and dirty]',
    'ciede2000 [slow and accurate]': 'ciede2000 [slow and accurate]',
    'CMC I:c [weird and slow]': 'CMC I:c [weird and slow]',
    'Euclidian + color values [fast and dirty]': 'Euclidian + color values [fast and dirty]',
    'brightness tune': 'brightness tune',
    'reset': 'reset',
    'constrast tune': 'constrast tune',
    'resize preview automatically': 'resize preview automatically',
    'serpentine (slightly suppresses dithering artefacts)': 'serpentine (slightly suppresses dithering artefacts)',
    'Into patterns': 'Into patterns',
    'Choose a palette': 'Choose a palette',
    // js and others
    'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file': 'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file',
    '[clipboard]': '[clipboard]',
    'Choose a image!': 'Choose a image!',
    'Invalid link!': 'Invalid link!',
    'Done in': 'Done in', //: Done in TIME ms
    'ms.': 'ms.', // milliseconds
    's.': 's.', // seconds
    'Unknown image loading error. Maybe CORS, so try to upload on Imgur': 'Unknown image loading error. Maybe CORS, so try to upload on Imgur',
    'If your image is big, go make a tea and watch Doctor Who': 'If your image is big, go make a tea and watch Doctor Who',
    'Final image size:': 'Final image size:',
    'Upload on imgur!': 'Upload on imgur!',
    'copy_canvas_btn': 'copy to Clipboard',
    'download_canvas_btn': 'download',
    'Imgur upload failed, try upload manually': 'Imgur upload failed, try upload manually',
    'insert_link_here': 'insert link here',
    'Failed to load game palettes!': 'Failed to load game palettes!',
    'URL/file/clipboard': 'URL/file/clipboard',

    // admin section
    // html
    'Backup Viewer': 'Backup Viewer',
    'SELECT CANVAS': 'SELECT CANVAS',
    'SELECT DAY': 'SELECT DAY',
    'SELECT TIME': 'SELECT TIME',
    'rollback': 'rollback',
    'Show chunk grid': 'Show chunk grid',
    'Crop chunks from': 'Crop chunks from',
    'to': 'to',
    'Crop rollback too': 'Crop rollback too',
    'IP Actions': 'IP Actions',
    'Blacklist': 'Blacklist',
	'Whitelist': 'Whitelist',
    'UnBlackist': 'UnBlackist',
    'UnWhitelist': 'UnWhitelist',
    'send': 'send',
    'set captchaEnabled state': 'set captchaEnabled state',
    'set': 'set',
    'set afterJoinDelay value': 'set afterJoinDelay value',
    'Canvas Actions': 'Canvas Actions',
    'Canvas': 'Canvas',
    'DO': 'DO',
    'wipe': 'wipe',
    'enlarge': 'enlarge',
    'top': 'top',
    'right': 'right',
    'bottom': 'bottom',
    'left': 'left',
    // js and others TODO
    'LOG IN': 'LOG IN',
    
}